name: Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-12] #  windows-2022 ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.7.0
        env:
          CIBW_ENVIRONMENT: >
            REPAIR_LIBRARY_PATH=${{runner.workspace}}/installs/highs/lib 
            LD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH 
            DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
            DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-listdeps {wheel} &&
            DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
