name: "Rebase fork from upstream"
on:
  schedule:
    - cron: '0 8 * * *' # Every day on 8:00 UTC
  push:
    paths:
    - '.github/workflows/upstream-rebase.yml'
  workflow_dispatch:

jobs:
  upstream-rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: git remote add upstream https://github.com/ERGO-Code/HiGHS.git
    - run: git fetch upstream
    - run: |
        echo "latestTag=$(git tag -l --sort -version:refname | head -n 1)" >> $GITHUB_ENV
        echo "$latestTag"
    #- run: git checkout main
    - run: git merge upstream/master
    - run: git push -f origin # main
    - uses: peter-evans/create-pull-request@v4
      with:
        title: "Rebase fork from upstream to $latestTag"
        branch: upstream-rebase
        commit-message: "[Bot] Rebase fork from upstream to $latestTag"
